<a href="https://colab.research.google.com/github/NickTorres04/Programacion-en-Python-UTEC/blob/main/CLASE_5_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd

# ***TEORIA MATRIZ ***

In [72]:
datos_4 = np.arange(10)
datos_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
type(datos_4)

numpy.ndarray

In [74]:
datos_4.min()

0

In [75]:
datos_4.max()

9

In [76]:
datos_4.mean()

4.5

In [77]:
datos_4.sum()

45

In [78]:
mat_1 = np.random.uniform(5,6,10)
mat_1

array([5.6342196 , 5.72771805, 5.28302026, 5.59958309, 5.67185166,
       5.78082945, 5.76265431, 5.9513525 , 5.50709767, 5.15180858])

In [79]:
mat_2 = np.random.uniform(1,2,10)
mat_2

array([1.47144296, 1.3697339 , 1.17630716, 1.43126029, 1.22210414,
       1.82646594, 1.96918507, 1.17349067, 1.51772065, 1.5355201 ])

In [80]:
mat_3 = np.random.uniform(-1,1,10)
mat_3

array([-0.88747947, -0.23285274, -0.07048766,  0.45085429,  0.66700027,
        0.94145176, -0.85414432, -0.26124506,  0.85250032,  0.76233857])

In [81]:
mat_1.ndim

1

In [82]:
mat_1 + mat_2 + mat_3

array([6.21818308, 6.86459921, 6.38883977, 7.48169768, 7.56095607,
       8.54874715, 6.87769506, 6.86359811, 7.87731864, 7.44966725])

In [83]:
# Obtener una serie a partir de una matriz (1D)
ser_mat_1 = pd.Series(mat_1)
ser_mat_1

0    5.634220
1    5.727718
2    5.283020
3    5.599583
4    5.671852
5    5.780829
6    5.762654
7    5.951353
8    5.507098
9    5.151809
dtype: float64

In [84]:
ser_mat_2 = pd.Series(mat_2)
ser_mat_2

0    1.471443
1    1.369734
2    1.176307
3    1.431260
4    1.222104
5    1.826466
6    1.969185
7    1.173491
8    1.517721
9    1.535520
dtype: float64

In [85]:
ser_mat_3 = pd.Series(mat_3)
ser_mat_3

0   -0.887479
1   -0.232853
2   -0.070488
3    0.450854
4    0.667000
5    0.941452
6   -0.854144
7   -0.261245
8    0.852500
9    0.762339
dtype: float64

In [86]:
%whos

Variable            Type         Data/Info
------------------------------------------
data_census         DataFrame           age          workc<...>[32560 rows x 12 columns]
data_demograficos   DataFrame         Indicadores  Fecundi<...>n24               11452  
datos_4             ndarray      10: 10 elems, type `int64`, 80 bytes
dic_datos           dict         n=3
drive               module       <module 'google.colab.dri<...>s/google/colab/drive.py'>
list_var_cat        list         n=8
list_var_num        list         n=3
mat_1               ndarray      10: 10 elems, type `float64`, 80 bytes
mat_2               ndarray      10: 10 elems, type `float64`, 80 bytes
mat_3               ndarray      10: 10 elems, type `float64`, 80 bytes
np                  module       <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
pd                  module       <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
res_data_dem        DataFrame                             <...>0  16320.

In [87]:
ser_mat_4 = ser_mat_1 + ser_mat_2 + ser_mat_3
ser_mat_4

0    6.218183
1    6.864599
2    6.388840
3    7.481698
4    7.560956
5    8.548747
6    6.877695
7    6.863598
8    7.877319
9    7.449667
dtype: float64

In [88]:
ser_mat_4.describe()

count    10.000000
mean      7.213130
std       0.707077
min       6.218183
25%       6.863848
50%       7.163681
75%       7.541141
max       8.548747
dtype: float64

In [89]:
np.array(["a","b","c"])

array(['a', 'b', 'c'], dtype='<U1')

In [90]:
pd.Series(np.array(["a","b","c"]),index=["x","y","z"])

x    a
y    b
z    c
dtype: object

In [91]:
dict_1 = {"Serie_1": ser_mat_1,
          "Serie_2": ser_mat_2,
          "Serie_3": ser_mat_3,
          "Serie_4": ser_mat_4
          }

In [92]:
type(dict_1)

dict

In [93]:
dict_1

{'Serie_1': 0    5.634220
 1    5.727718
 2    5.283020
 3    5.599583
 4    5.671852
 5    5.780829
 6    5.762654
 7    5.951353
 8    5.507098
 9    5.151809
 dtype: float64,
 'Serie_2': 0    1.471443
 1    1.369734
 2    1.176307
 3    1.431260
 4    1.222104
 5    1.826466
 6    1.969185
 7    1.173491
 8    1.517721
 9    1.535520
 dtype: float64,
 'Serie_3': 0   -0.887479
 1   -0.232853
 2   -0.070488
 3    0.450854
 4    0.667000
 5    0.941452
 6   -0.854144
 7   -0.261245
 8    0.852500
 9    0.762339
 dtype: float64,
 'Serie_4': 0    6.218183
 1    6.864599
 2    6.388840
 3    7.481698
 4    7.560956
 5    8.548747
 6    6.877695
 7    6.863598
 8    7.877319
 9    7.449667
 dtype: float64}

In [94]:
data = pd.DataFrame(dict_1)

In [95]:
data.head(5)

Serie_1   Serie_2   Serie_3   Serie_4
0  5.634220  1.471443 -0.887479  6.218183
1  5.727718  1.369734 -0.232853  6.864599
2  5.283020  1.176307 -0.070488  6.388840
3  5.599583  1.431260  0.450854  7.481698
4  5.671852  1.222104  0.667000  7.560956

In [96]:
data.shape

(10, 4)

# ***USANDO EL EXCEL DE CENSUS***

In [10]:
import sys

sys.path[0]

'/content'

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#/content/drive/MyDrive/census.csv

In [13]:
data_census = pd.read_csv("drive/MyDrive/census.csv", sep=",")

In [14]:
type(data_census)

pandas.core.frame.DataFrame

In [15]:
data_census.head(2)

age          workclass   education  education_num       marital_status  \
0   39          State-gov   Bachelors             13        Never-married   
1   50   Self-emp-not-inc   Bachelors             13   Married-civ-spouse   

         occupation    relationship    race gender  hours_per_week  \
0      Adm-clerical   Not-in-family   White   Male              40   
1   Exec-managerial         Husband   White   Male              13   

   native_country  greater_than_50k  
0   United-States                 0  
1   United-States                 0

In [16]:
data_census.shape

(32560, 12)

In [17]:
data_census.shape[0] # Nro de filas del DataFrame

32560

In [18]:
data_census.shape[1] # Nro de columnas del DataFrame

12

In [19]:
data_census.dtypes

age                  int64
workclass           object
education           object
education_num        int64
marital_status      object
occupation          object
relationship        object
race                object
gender              object
hours_per_week       int64
native_country      object
greater_than_50k     int64
dtype: object

In [20]:
data_census.describe()

age  education_num  hours_per_week  greater_than_50k
count  32560.000000   32560.000000    32560.000000      32560.000000
mean      38.581849      10.080682       40.437469          0.240817
std       13.640593       2.572760       12.347618          0.427586
min       17.000000       1.000000        1.000000          0.000000
25%       28.000000       9.000000       40.000000          0.000000
50%       37.000000      10.000000       40.000000          0.000000
75%       48.000000      12.000000       45.000000          0.000000
max       90.000000      16.000000       99.000000          1.000000

In [21]:
data_census.describe(include='all').transpose()

count unique                  top   freq       mean  \
age               32560.0    NaN                  NaN    NaN  38.581849   
workclass           30724      8              Private  22695        NaN   
education           32560     16              HS-grad  10501        NaN   
education_num     32560.0    NaN                  NaN    NaN  10.080682   
marital_status      32560      7   Married-civ-spouse  14976        NaN   
occupation          30717     14       Prof-specialty   4140        NaN   
relationship        32560      6              Husband  13193        NaN   
race                32560      5                White  27815        NaN   
gender              32560      2                 Male  21790        NaN   
hours_per_week    32560.0    NaN                  NaN    NaN  40.437469   
native_country      31977     40        United-States  29170        NaN   
greater_than_50k  32560.0    NaN                  NaN    NaN   0.240817   

                        std   min   25%   50%   75%   max  
age               13.640593  17.0  28.0  37.0  48.0  90.0  
workclass               NaN   NaN   NaN   NaN   NaN   NaN  
education               NaN   NaN   NaN   NaN   NaN   NaN  
education_num       2.57276   1.0   9.0  10.0  12.0  16.0  
marital_status          NaN   NaN   NaN   NaN   NaN   NaN  
occupation              NaN   NaN   NaN   NaN   NaN   NaN  
relationship            NaN   NaN   NaN   NaN   NaN   NaN  
race                    NaN   NaN   NaN   NaN   NaN   NaN  
gender                  NaN   NaN   NaN   NaN   NaN   NaN  
hours_per_week    12.347618   1.0  40.0  40.0  45.0  99.0  
native_country          NaN   NaN   NaN   NaN   NaN   NaN  
greater_than_50k   0.427586   0.0   0.0   0.0   0.0   1.0

In [22]:
data_census.columns.to_list()

['age',
 'workclass',
 'education',
 'education_num',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'hours_per_week',
 'native_country',
 'greater_than_50k']

In [23]:
list_var_num = ['age',
 'education_num',
 'hours_per_week']

In [24]:
list_var_num

['age', 'education_num', 'hours_per_week']

In [25]:
type(list_var_num)

list

In [26]:
res_var_num = data_census[list_var_num].describe().transpose()
res_var_num

count       mean        std   min   25%   50%   75%   max
age             32560.0  38.581849  13.640593  17.0  28.0  37.0  48.0  90.0
education_num   32560.0  10.080682   2.572760   1.0   9.0  10.0  12.0  16.0
hours_per_week  32560.0  40.437469  12.347618   1.0  40.0  40.0  45.0  99.0

In [27]:
list_var_cat = ['workclass',
 'education',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'native_country']

In [28]:
list_var_cat

['workclass',
 'education',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'native_country']

In [29]:
res_var_cat = data_census[list_var_cat].describe().transpose()
res_var_cat

count unique                  top   freq
workclass       30724      8              Private  22695
education       32560     16              HS-grad  10501
marital_status  32560      7   Married-civ-spouse  14976
occupation      30717     14       Prof-specialty   4140
relationship    32560      6              Husband  13193
race            32560      5                White  27815
gender          32560      2                 Male  21790
native_country  31977     40        United-States  29170

In [30]:
res_var_cat_ = data_census[list_var_cat].describe().transpose().reset_index()
res_var_cat_

index  count unique                  top   freq
0       workclass  30724      8              Private  22695
1       education  32560     16              HS-grad  10501
2  marital_status  32560      7   Married-civ-spouse  14976
3      occupation  30717     14       Prof-specialty   4140
4    relationship  32560      6              Husband  13193
5            race  32560      5                White  27815
6          gender  32560      2                 Male  21790
7  native_country  31977     40        United-States  29170

In [31]:
res_var_cat_ = res_var_cat_.rename(columns={'index':'Variable'})
res_var_cat_

Variable  count unique                  top   freq
0       workclass  30724      8              Private  22695
1       education  32560     16              HS-grad  10501
2  marital_status  32560      7   Married-civ-spouse  14976
3      occupation  30717     14       Prof-specialty   4140
4    relationship  32560      6              Husband  13193
5            race  32560      5                White  27815
6          gender  32560      2                 Male  21790
7  native_country  31977     40        United-States  29170

In [32]:
res_var_cat_["count"]

0    30724
1    32560
2    32560
3    30717
4    32560
5    32560
6    32560
7    31977
Name: count, dtype: object

In [33]:
res_var_cat_["pct_data_faltante"] = (1 -  (res_var_cat_["count"]/data_census.shape[0]))*100
res_var_cat_

Variable  count unique                  top   freq pct_data_faltante
0       workclass  30724      8              Private  22695          5.638821
1       education  32560     16              HS-grad  10501               0.0
2  marital_status  32560      7   Married-civ-spouse  14976               0.0
3      occupation  30717     14       Prof-specialty   4140          5.660319
4    relationship  32560      6              Husband  13193               0.0
5            race  32560      5                White  27815               0.0
6          gender  32560      2                 Male  21790               0.0
7  native_country  31977     40        United-States  29170          1.790541

In [34]:
# Crear un campo que vamos a llamar "pct_cat_prin"

res_var_cat_["pct_cat_prin"] = (res_var_cat_["freq"] / res_var_cat_["count"])*100
res_var_cat_

Variable  count unique                  top   freq pct_data_faltante  \
0       workclass  30724      8              Private  22695          5.638821   
1       education  32560     16              HS-grad  10501               0.0   
2  marital_status  32560      7   Married-civ-spouse  14976               0.0   
3      occupation  30717     14       Prof-specialty   4140          5.660319   
4    relationship  32560      6              Husband  13193               0.0   
5            race  32560      5                White  27815               0.0   
6          gender  32560      2                 Male  21790               0.0   
7  native_country  31977     40        United-States  29170          1.790541   

  pct_cat_prin  
0    73.867335  
1    32.251229  
2    45.995086  
3    13.477879  
4    40.519042  
5    85.426904  
6    66.922604  
7    91.221816

In [35]:
res_var_cat_["pct_cat_prin"]

0    73.867335
1    32.251229
2    45.995086
3    13.477879
4    40.519042
5    85.426904
6    66.922604
7    91.221816
Name: pct_cat_prin, dtype: object

In [36]:
type(res_var_cat_["pct_cat_prin"])

pandas.core.series.Series

In [ ]:
res_var_cat_["pct_cat_prin"].values

array([73.86733498242415, 32.2512285012285, 45.995085995085994,
       13.477878699091708, 40.51904176904177, 85.42690417690417,
       66.92260442260442, 91.22181568002001], dtype=object)

In [37]:
type(res_var_cat_["pct_cat_prin"].values)

numpy.ndarray

In [38]:
res_var_cat_["pct_cat_prin"] = np.round(list(res_var_cat_["pct_cat_prin"].values),2)
res_var_cat_

Variable  count unique                  top   freq pct_data_faltante  \
0       workclass  30724      8              Private  22695          5.638821   
1       education  32560     16              HS-grad  10501               0.0   
2  marital_status  32560      7   Married-civ-spouse  14976               0.0   
3      occupation  30717     14       Prof-specialty   4140          5.660319   
4    relationship  32560      6              Husband  13193               0.0   
5            race  32560      5                White  27815               0.0   
6          gender  32560      2                 Male  21790               0.0   
7  native_country  31977     40        United-States  29170          1.790541   

   pct_cat_prin  
0         73.87  
1         32.25  
2         46.00  
3         13.48  
4         40.52  
5         85.43  
6         66.92  
7         91.22

In [39]:
res_var_cat_["pct_data_faltante"] = np.round(list(res_var_cat_["pct_data_faltante"].values),2)
res_var_cat_

Variable  count unique                  top   freq  \
0       workclass  30724      8              Private  22695   
1       education  32560     16              HS-grad  10501   
2  marital_status  32560      7   Married-civ-spouse  14976   
3      occupation  30717     14       Prof-specialty   4140   
4    relationship  32560      6              Husband  13193   
5            race  32560      5                White  27815   
6          gender  32560      2                 Male  21790   
7  native_country  31977     40        United-States  29170   

   pct_data_faltante  pct_cat_prin  
0               5.64         73.87  
1               0.00         32.25  
2               0.00         46.00  
3               5.66         13.48  
4               0.00         40.52  
5               0.00         85.43  
6               0.00         66.92  
7               1.79         91.22

In [40]:
type(res_var_cat_)

pandas.core.frame.DataFrame

In [41]:
data_census['workclass']

0                State-gov
1         Self-emp-not-inc
2                  Private
3                  Private
4                  Private
               ...        
32555              Private
32556              Private
32557              Private
32558              Private
32559         Self-emp-inc
Name: workclass, Length: 32560, dtype: object

In [42]:
data_census['workclass'].unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', nan, ' Self-emp-inc', ' Without-pay',
       ' Never-worked'], dtype=object)

In [43]:
data_census['workclass'].nunique()

8

In [44]:
data_census['workclass'].isna()

0        False
1        False
2        False
3        False
4        False
         ...  
32555    False
32556    False
32557    False
32558    False
32559    False
Name: workclass, Length: 32560, dtype: bool

In [45]:
data_census['workclass'].isna().value_counts()

workclass
False    30724
True      1836
Name: count, dtype: int64

In [46]:
data_census["marital_status"].unique()

array([' Never-married', ' Married-civ-spouse', ' Divorced',
       ' Married-spouse-absent', ' Separated', ' Married-AF-spouse',
       ' Widowed'], dtype=object)

In [47]:
type(data_census["marital_status"].unique())

numpy.ndarray

In [48]:
serie_ms = data_census["marital_status"].unique()
serie_ms

array([' Never-married', ' Married-civ-spouse', ' Divorced',
       ' Married-spouse-absent', ' Separated', ' Married-AF-spouse',
       ' Widowed'], dtype=object)

In [49]:
serie_e = data_census["education"].unique()
serie_e

array([' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th',
       ' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th',
       ' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th',
       ' Preschool', ' 12th'], dtype=object)

In [50]:
serie_o = data_census["occupation"].unique()
serie_o

array([' Adm-clerical', ' Exec-managerial', ' Handlers-cleaners',
       ' Prof-specialty', ' Other-service', ' Sales', ' Craft-repair',
       ' Transport-moving', ' Farming-fishing', ' Machine-op-inspct',
       ' Tech-support', nan, ' Protective-serv', ' Armed-Forces',
       ' Priv-house-serv'], dtype=object)

In [51]:
dic_datos = {
    "Estado_Civil" : serie_ms,
    "Grado_instruccion" : serie_e,
    "Ocupacion" : serie_o
}

In [52]:
type(dic_datos)

dict

In [53]:
dic_datos

{'Estado_Civil': array([' Never-married', ' Married-civ-spouse', ' Divorced',
        ' Married-spouse-absent', ' Separated', ' Married-AF-spouse',
        ' Widowed'], dtype=object),
 'Grado_instruccion': array([' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th',
        ' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th',
        ' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th',
        ' Preschool', ' 12th'], dtype=object),
 'Ocupacion': array([' Adm-clerical', ' Exec-managerial', ' Handlers-cleaners',
        ' Prof-specialty', ' Other-service', ' Sales', ' Craft-repair',
        ' Transport-moving', ' Farming-fishing', ' Machine-op-inspct',
        ' Tech-support', nan, ' Protective-serv', ' Armed-Forces',
        ' Priv-house-serv'], dtype=object)}

In [54]:
dic_datos['Estado_Civil']

array([' Never-married', ' Married-civ-spouse', ' Divorced',
       ' Married-spouse-absent', ' Separated', ' Married-AF-spouse',
       ' Widowed'], dtype=object)

In [55]:
pd.Series(dic_datos)

Estado_Civil         [ Never-married,  Married-civ-spouse,  Divorce...
Grado_instruccion    [ Bachelors,  HS-grad,  11th,  Masters,  9th, ...
Ocupacion            [ Adm-clerical,  Exec-managerial,  Handlers-cl...
dtype: object

In [56]:
pd.DataFrame(pd.Series(dic_datos))

0
Estado_Civil       [ Never-married,  Married-civ-spouse,  Divorce...
Grado_instruccion  [ Bachelors,  HS-grad,  11th,  Masters,  9th, ...
Ocupacion          [ Adm-clerical,  Exec-managerial,  Handlers-cl...

# ***EXCEL DATOS DEMOGRAFICOS***

In [61]:
# /content/drive/MyDrive/DATOS/datosDemograficos.xlsx
data_demograficos = pd.read_excel("drive/MyDrive/DATOS/datosDemograficos.xlsx",sheet_name="Data")

In [62]:
data_demograficos.head(2)

Indicadores  Fecundidad  Mortalidad  TasaMortalidadxMil  EsperanzaVida  \
0        Puno       30108        9951                6.86          71.44   
1  San Martín       16074        4889                5.63          72.45   

   EVSoloHombres  EVSoloMujeres  TasaMortalidadInfantilxMilNacidos  \
0          68.77          74.25                              26.82   
1          69.65          75.40                              17.53   

   CrecimientoNatural  
0               20157  
1               11185

In [67]:
res_data_dem = data_demograficos.describe().transpose()

In [68]:
res_data_dem

count          mean           std      min  \
Fecundidad                          25.0  22874.400000  30817.223005  2571.00   
Mortalidad                          25.0   7265.280000  10451.427130   660.00   
TasaMortalidadxMil                  24.0      5.711667      0.580777     4.54   
EsperanzaVida                       25.0     74.059600      2.375038    70.93   
EVSoloHombres                       25.0     71.337200      2.315498    68.53   
EVSoloMujeres                       25.0     76.919200      2.443766    73.45   
TasaMortalidadInfantilxMilNacidos   25.0     16.984000      5.434434     7.81   
CrecimientoNatural                  25.0  15609.120000  20409.736145  1566.00   

                                         25%        50%        75%        max  
Fecundidad                         8872.0000  16074.000  24385.000  163089.00  
Mortalidad                         2788.0000   5234.000   8450.000   55201.00  
TasaMortalidadxMil                    5.3975      5.545      5.985       6.97  
EsperanzaVida                        71.9900     73.290     76.450      78.38  
EVSoloHombres                        69.2400     70.710     73.650      75.68  
EVSoloMujeres                        74.8700     76.000     79.390      81.22  
TasaMortalidadInfantilxMilNacidos    11.7700     16.890     20.000      26.82  
CrecimientoNatural                 5852.0000  11452.000  16320.000  107888.00

In [71]:
#/content/drive/MyDrive/DATOS
res_data_dem.to_csv("drive/MyDrive/DATOS/resumen_datos_dem.csv")