<a href="https://colab.research.google.com/github/NickTorres04/Programacion-en-Python-UTEC/blob/main/CLASE_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
datos_4 = np.arange(10)
datos_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(datos_4)

numpy.ndarray

In [ ]:
datos_4.min()

0

In [ ]:
datos_4.max()

9

In [ ]:
datos_4.mean()

4.5

In [ ]:
datos_4.sum()

45

In [ ]:
mat_1 = np.random.uniform(5,6,10)
mat_1

array([5.49296516, 5.89961068, 5.76506096, 5.34129764, 5.0245782 ,
       5.86050786, 5.48590243, 5.16513287, 5.64896449, 5.63776515])

In [ ]:
mat_2 = np.random.uniform(1,2,10)
mat_2

array([1.62532865, 1.79972759, 1.14909685, 1.71602288, 1.62418376,
       1.08128735, 1.17114015, 1.70048699, 1.03451796, 1.70415928])

In [ ]:
mat_3 = np.random.uniform(-1,1,10)
mat_3

array([ 0.2465524 , -0.28527274, -0.19500466,  0.51756273, -0.37189739,
       -0.61351264, -0.59942443, -0.53601408,  0.6695826 ,  0.85121274])

In [ ]:
mat_1.ndim

1

In [ ]:
mat_1 + mat_2 + mat_3

array([7.36484621, 7.41406553, 6.71915315, 7.57488325, 6.27686456,
       6.32828257, 6.05761816, 6.32960577, 7.35306504, 8.19313717])

In [ ]:
# Obtener una serie a partir de una matriz (1D)
ser_mat_1 = pd.Series(mat_1)
ser_mat_1

0    5.492965
1    5.899611
2    5.765061
3    5.341298
4    5.024578
5    5.860508
6    5.485902
7    5.165133
8    5.648964
9    5.637765
dtype: float64

In [ ]:
ser_mat_2 = pd.Series(mat_2)
ser_mat_2

0    1.625329
1    1.799728
2    1.149097
3    1.716023
4    1.624184
5    1.081287
6    1.171140
7    1.700487
8    1.034518
9    1.704159
dtype: float64

In [ ]:
ser_mat_3 = pd.Series(mat_3)
ser_mat_3

0    0.246552
1   -0.285273
2   -0.195005
3    0.517563
4   -0.371897
5   -0.613513
6   -0.599424
7   -0.536014
8    0.669583
9    0.851213
dtype: float64

In [ ]:
%whos

Variable    Type         Data/Info
----------------------------------
data        DataFrame        Serie_1   Serie_2   S<...>80536  0.158857  7.638162
datos_4     ndarray      10: 10 elems, type `int64`, 80 bytes
dict_1      dict         n=4
mat_1       ndarray      10: 10 elems, type `float64`, 80 bytes
mat_2       ndarray      10: 10 elems, type `float64`, 80 bytes
mat_3       ndarray      10: 10 elems, type `float64`, 80 bytes
np          module       <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
pd          module       <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
ser_mat_1   Series       0    5.492965\n1    5.899<...> 5.637765\ndtype: float64
ser_mat_2   Series       0    1.625329\n1    1.799<...> 1.704159\ndtype: float64
ser_mat_3   Series       0    0.246552\n1   -0.285<...> 0.851213\ndtype: float64
ser_mat_4   Series       0    7.094880\n1    7.747<...> 7.638162\ndtype: float64
sys         module       <module 'sys' (built-in)>


In [ ]:
ser_mat_4 = ser_mat_1 + ser_mat_2 + ser_mat_3
ser_mat_4

0    7.364846
1    7.414066
2    6.719153
3    7.574883
4    6.276865
5    6.328283
6    6.057618
7    6.329606
8    7.353065
9    8.193137
dtype: float64

In [ ]:
ser_mat_4.describe()

count    10.000000
mean      6.961152
std       0.711704
min       6.057618
25%       6.328613
50%       7.036109
75%       7.401761
max       8.193137
dtype: float64

In [ ]:
np.array(["a","b","c"])

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
pd.Series(np.array(["a","b","c"]),index=["x","y","z"])

x    a
y    b
z    c
dtype: object

In [ ]:
dict_1 = {"Serie_1": ser_mat_1,
          "Serie_2": ser_mat_2,
          "Serie_3": ser_mat_3,
          "Serie_4": ser_mat_4
          }

In [ ]:
type(dict_1)

dict

In [ ]:
dict_1

{'Serie_1': 0    5.492965
 1    5.899611
 2    5.765061
 3    5.341298
 4    5.024578
 5    5.860508
 6    5.485902
 7    5.165133
 8    5.648964
 9    5.637765
 dtype: float64,
 'Serie_2': 0    1.625329
 1    1.799728
 2    1.149097
 3    1.716023
 4    1.624184
 5    1.081287
 6    1.171140
 7    1.700487
 8    1.034518
 9    1.704159
 dtype: float64,
 'Serie_3': 0    0.246552
 1   -0.285273
 2   -0.195005
 3    0.517563
 4   -0.371897
 5   -0.613513
 6   -0.599424
 7   -0.536014
 8    0.669583
 9    0.851213
 dtype: float64,
 'Serie_4': 0    7.364846
 1    7.414066
 2    6.719153
 3    7.574883
 4    6.276865
 5    6.328283
 6    6.057618
 7    6.329606
 8    7.353065
 9    8.193137
 dtype: float64}

In [ ]:
data = pd.DataFrame(dict_1)

In [ ]:
data.head(5)

Serie_1   Serie_2   Serie_3   Serie_4
0  5.492965  1.625329  0.246552  7.364846
1  5.899611  1.799728 -0.285273  7.414066
2  5.765061  1.149097 -0.195005  6.719153
3  5.341298  1.716023  0.517563  7.574883
4  5.024578  1.624184 -0.371897  6.276865

In [ ]:
data.shape

(10, 4)

In [ ]:
import sys

sys.path[0]

'/content'

In [ ]:
data_census = pd.read_csv("Data/census.csv", sep=",")

In [ ]:
type(data_census)

pandas.core.frame.DataFrame

In [ ]:
data_census.head(2)

age          workclass   education  education_num       marital_status  \
0   39          State-gov   Bachelors             13        Never-married   
1   50   Self-emp-not-inc   Bachelors             13   Married-civ-spouse   

         occupation    relationship    race gender  hours_per_week  \
0      Adm-clerical   Not-in-family   White   Male              40   
1   Exec-managerial         Husband   White   Male              13   

   native_country  greater_than_50k  
0   United-States                 0  
1   United-States                 0

In [ ]:
data_census.shape

(32560, 12)

In [ ]:
data_census.shape[0] # Nro de filas del DataFrame

32560

In [ ]:
data_census.shape[1] # Nro de columnas del DataFrame

12

In [ ]:
data_census.dtypes

age                  int64
workclass           object
education           object
education_num        int64
marital_status      object
occupation          object
relationship        object
race                object
gender              object
hours_per_week       int64
native_country      object
greater_than_50k     int64
dtype: object

In [ ]:
data_census.describe()

age  education_num  hours_per_week  greater_than_50k
count  32560.000000   32560.000000    32560.000000      32560.000000
mean      38.581849      10.080682       40.437469          0.240817
std       13.640593       2.572760       12.347618          0.427586
min       17.000000       1.000000        1.000000          0.000000
25%       28.000000       9.000000       40.000000          0.000000
50%       37.000000      10.000000       40.000000          0.000000
75%       48.000000      12.000000       45.000000          0.000000
max       90.000000      16.000000       99.000000          1.000000

In [ ]:
data_census.describe(include='all').transpose()

count unique                  top   freq       mean  \
age               32560.0    NaN                  NaN    NaN  38.581849   
workclass           30724      8              Private  22695        NaN   
education           32560     16              HS-grad  10501        NaN   
education_num     32560.0    NaN                  NaN    NaN  10.080682   
marital_status      32560      7   Married-civ-spouse  14976        NaN   
occupation          30717     14       Prof-specialty   4140        NaN   
relationship        32560      6              Husband  13193        NaN   
race                32560      5                White  27815        NaN   
gender              32560      2                 Male  21790        NaN   
hours_per_week    32560.0    NaN                  NaN    NaN  40.437469   
native_country      31977     40        United-States  29170        NaN   
greater_than_50k  32560.0    NaN                  NaN    NaN   0.240817   

                        std   min   25%   50%   75%   max  
age               13.640593  17.0  28.0  37.0  48.0  90.0  
workclass               NaN   NaN   NaN   NaN   NaN   NaN  
education               NaN   NaN   NaN   NaN   NaN   NaN  
education_num       2.57276   1.0   9.0  10.0  12.0  16.0  
marital_status          NaN   NaN   NaN   NaN   NaN   NaN  
occupation              NaN   NaN   NaN   NaN   NaN   NaN  
relationship            NaN   NaN   NaN   NaN   NaN   NaN  
race                    NaN   NaN   NaN   NaN   NaN   NaN  
gender                  NaN   NaN   NaN   NaN   NaN   NaN  
hours_per_week    12.347618   1.0  40.0  40.0  45.0  99.0  
native_country          NaN   NaN   NaN   NaN   NaN   NaN  
greater_than_50k   0.427586   0.0   0.0   0.0   0.0   1.0

In [ ]:
data_census.columns.to_list()

['age',
 'workclass',
 'education',
 'education_num',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'hours_per_week',
 'native_country',
 'greater_than_50k']

In [ ]:
list_var_num = ['age',
 'education_num',
 'hours_per_week']

In [ ]:
list_var_num

['age', 'education_num', 'hours_per_week']

In [ ]:
type(list_var_num)

list

In [ ]:
res_var_num = data_census[list_var_num].describe().transpose()
res_var_num

count       mean        std   min   25%   50%   75%   max
age             32560.0  38.581849  13.640593  17.0  28.0  37.0  48.0  90.0
education_num   32560.0  10.080682   2.572760   1.0   9.0  10.0  12.0  16.0
hours_per_week  32560.0  40.437469  12.347618   1.0  40.0  40.0  45.0  99.0

In [ ]:
list_var_cat = ['workclass',
 'education',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'native_country']

In [ ]:
list_var_cat

['workclass',
 'education',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'native_country']

In [ ]:
res_var_cat = data_census[list_var_cat].describe().transpose()
res_var_cat

count unique                  top   freq
workclass       30724      8              Private  22695
education       32560     16              HS-grad  10501
marital_status  32560      7   Married-civ-spouse  14976
occupation      30717     14       Prof-specialty   4140
relationship    32560      6              Husband  13193
race            32560      5                White  27815
gender          32560      2                 Male  21790
native_country  31977     40        United-States  29170

In [ ]:
res_var_cat_ = data_census[list_var_cat].describe().transpose().reset_index()
res_var_cat_

index  count unique                  top   freq
0       workclass  30724      8              Private  22695
1       education  32560     16              HS-grad  10501
2  marital_status  32560      7   Married-civ-spouse  14976
3      occupation  30717     14       Prof-specialty   4140
4    relationship  32560      6              Husband  13193
5            race  32560      5                White  27815
6          gender  32560      2                 Male  21790
7  native_country  31977     40        United-States  29170

In [ ]:
res_var_cat_ = res_var_cat_.rename(columns={'index':'Variable'})
res_var_cat_

Variable  count unique                  top   freq
0       workclass  30724      8              Private  22695
1       education  32560     16              HS-grad  10501
2  marital_status  32560      7   Married-civ-spouse  14976
3      occupation  30717     14       Prof-specialty   4140
4    relationship  32560      6              Husband  13193
5            race  32560      5                White  27815
6          gender  32560      2                 Male  21790
7  native_country  31977     40        United-States  29170

In [ ]:
res_var_cat_["count"]

0    30724
1    32560
2    32560
3    30717
4    32560
5    32560
6    32560
7    31977
Name: count, dtype: object

In [ ]:
res_var_cat_["pct_data_faltante"] = (1 -  (res_var_cat_["count"]/data_census.shape[0]))*100
res_var_cat_

Variable  count unique                  top   freq pct_data_faltante
0       workclass  30724      8              Private  22695          5.638821
1       education  32560     16              HS-grad  10501               0.0
2  marital_status  32560      7   Married-civ-spouse  14976               0.0
3      occupation  30717     14       Prof-specialty   4140          5.660319
4    relationship  32560      6              Husband  13193               0.0
5            race  32560      5                White  27815               0.0
6          gender  32560      2                 Male  21790               0.0
7  native_country  31977     40        United-States  29170          1.790541

In [ ]:
# Crear un campo que vamos a llamar "pct_cat_prin"

res_var_cat_["pct_cat_prin"] = (res_var_cat_["freq"] / res_var_cat_["count"])*100
res_var_cat_

Variable  count unique                  top   freq pct_data_faltante  \
0       workclass  30724      8              Private  22695          5.638821   
1       education  32560     16              HS-grad  10501               0.0   
2  marital_status  32560      7   Married-civ-spouse  14976               0.0   
3      occupation  30717     14       Prof-specialty   4140          5.660319   
4    relationship  32560      6              Husband  13193               0.0   
5            race  32560      5                White  27815               0.0   
6          gender  32560      2                 Male  21790               0.0   
7  native_country  31977     40        United-States  29170          1.790541   

  pct_cat_prin  
0    73.867335  
1    32.251229  
2    45.995086  
3    13.477879  
4    40.519042  
5    85.426904  
6    66.922604  
7    91.221816

In [ ]:
res_var_cat_["pct_cat_prin"]

0    73.867335
1    32.251229
2    45.995086
3    13.477879
4    40.519042
5    85.426904
6    66.922604
7    91.221816
Name: pct_cat_prin, dtype: object

In [ ]:
type(res_var_cat_["pct_cat_prin"])

pandas.core.series.Series

In [ ]:
res_var_cat_["pct_cat_prin"].values

array([73.86733498242415, 32.2512285012285, 45.995085995085994,
       13.477878699091708, 40.51904176904177, 85.42690417690417,
       66.92260442260442, 91.22181568002001], dtype=object)

In [ ]:
type(res_var_cat_["pct_cat_prin"].values)

numpy.ndarray

In [ ]:
res_var_cat_["pct_cat_prin"] = np.round(list(res_var_cat_["pct_cat_prin"].values),2)
res_var_cat_

Variable  count unique                  top   freq pct_data_faltante  \
0       workclass  30724      8              Private  22695          5.638821   
1       education  32560     16              HS-grad  10501               0.0   
2  marital_status  32560      7   Married-civ-spouse  14976               0.0   
3      occupation  30717     14       Prof-specialty   4140          5.660319   
4    relationship  32560      6              Husband  13193               0.0   
5            race  32560      5                White  27815               0.0   
6          gender  32560      2                 Male  21790               0.0   
7  native_country  31977     40        United-States  29170          1.790541   

   pct_cat_prin  
0         73.87  
1         32.25  
2         46.00  
3         13.48  
4         40.52  
5         85.43  
6         66.92  
7         91.22

In [ ]:
res_var_cat_["pct_data_faltante"] = np.round(list(res_var_cat_["pct_data_faltante"].values),2)
res_var_cat_

Variable  count unique                  top   freq  \
0       workclass  30724      8              Private  22695   
1       education  32560     16              HS-grad  10501   
2  marital_status  32560      7   Married-civ-spouse  14976   
3      occupation  30717     14       Prof-specialty   4140   
4    relationship  32560      6              Husband  13193   
5            race  32560      5                White  27815   
6          gender  32560      2                 Male  21790   
7  native_country  31977     40        United-States  29170   

   pct_data_faltante  pct_cat_prin  
0               5.64         73.87  
1               0.00         32.25  
2               0.00         46.00  
3               5.66         13.48  
4               0.00         40.52  
5               0.00         85.43  
6               0.00         66.92  
7               1.79         91.22

In [ ]:
type(res_var_cat_)

In [ ]:
data_census['workclass']

In [ ]:
data_census['workclass'].unique()

In [ ]:
data_census['workclass'].nunique()

In [ ]:
data_census['workclass'].isna()

In [ ]:
data_census['workclass'].isna().value_counts()

In [ ]:
data_census["marital_status"].unique()

In [ ]:
type(data_census["marital_status"].unique())

In [ ]:
serie_ms = data_census["marital_status"].unique()
serie_ms

In [ ]:
serie_e = data_census["education"].unique()
serie_e

In [ ]:
serie_o = data_census["occupation"].unique()
serie_o

In [ ]:
dic_datos = {
    "Estado_Civil" : serie_ms,
    "Grado_instruccion" : serie_e,
    "Ocupacion" : serie_o
}

In [ ]:
type(dic_datos)

In [ ]:
dic_datos

In [ ]:
dic_datos['Estado_Civil']

In [ ]:
pd.Series(dic_datos)

In [ ]:
pd.DataFrame(pd.Series(dic_datos))

In [ ]:
pd.DataFrame(dic_datos)

In [ ]:
data_demograficos = pd.read_excel("Data/datosDemograficos.xlsx", sheet_name="Data")

In [ ]:
data_demograficos.head(2)

In [ ]:
res_data_dem = data_demograficos.describe().transpose()

In [ ]:
res_data_dem

In [ ]:
res_data_dem.to_csv("Data/resumen_datos_dem.csv")