<a href="https://colab.research.google.com/github/NickTorres04/Programacion-en-Python-UTEC/blob/main/mod2_clase3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [2]:
# Arreglo que consume menos memoria.
import numpy as np

In [5]:
lista_1 = [1,3,5]
print(lista_1)
sum(lista_1)

[1, 3, 5]


9

In [9]:
type(lista_1)

list

In [10]:
mat_1=([2,4,5])
type(mat_1)

list

In [12]:
lista_1.append(8)
print(lista_1)

[1, 3, 5, 8, 8]


In [13]:
vector = np.array([1, 2, 3, 4, 5])

In [14]:
type(vector)

numpy.ndarray

In [16]:
#listas:
l1 = [1,2,3]
l2 = [4,5,6]
l1+l2
print(l1+l2)

[1, 2, 3, 4, 5, 6]


In [19]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(f"Arreglo de Numpy 1 {a1}")
print(f"Arreglo de Numpy 1 {a2}")
print(f"Arreglo de Numpy a1 + a2 {a1+a2}")
print(f"Arreglo de Numpy a1 * a2 {a1*a2}")

Arreglo de Numpy 1 [1 2 3]
Arreglo de Numpy 1 [4 5 6]
Arreglo de Numpy a1 + a2 [5 7 9]
Arreglo de Numpy a1 * a2 [ 4 10 18]


In [20]:
mat_3 =np.array([1,2,3,4,5,6])
mat_3

array([1, 2, 3, 4, 5, 6])

## matriz de DOS DIMENSIONES

In [21]:
# Matriz en 2D
mat_4 = np.array([[1,2,3],[4,5,6]])
mat_4

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
mat_5 = np.array([[1],[4],[6]])
mat_5

array([[1],
       [4],
       [6]])

In [25]:
lista_2  =  [1,2,3,4,5]
print(f"La lista es : {lista_2}\n")
print(f"El tipo del objeto es: {type(lista_2)}")

La lista es : [1, 2, 3, 4, 5]

El tipo del objeto es: <class 'list'>


In [27]:
mat_5 =  np.array(lista_2)
print(f"La lista es : {mat_5}\n")
print(f"El tipo del objeto es: {type(mat_5)}")

La lista es : [1 2 3 4 5]

El tipo del objeto es: <class 'numpy.ndarray'>


In [28]:
lista_3  =  [[1,2,3],[4,5,6],[7,8,9]]
print(f"La lista es : {lista_3}\n")
print(f"El tipo del objeto es: {type(lista_3)}")

La lista es : [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

El tipo del objeto es: <class 'list'>


In [31]:
mat_6  =  np.array(lista_3)
print(f"La lista es :\n {mat_6}")
print(f"El tipo del objeto es: {type(mat_6)}")

La lista es :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
El tipo del objeto es: <class 'numpy.ndarray'>


In [43]:
mat_7 = np.arange(20).reshape(4,5) #FILAS , COLUMNAS
print(f"La lista es :\n {mat_7}")
print(f"El tipo del objeto es: {type(mat_7)}")
print(f"El numero de dimensiones es: {mat_7.ndim}")
print(f"el numero de elementos es: {mat_7.size}")
print(f"El tanaño de las dimensiones del objeto es: {mat_7.shape}")

La lista es :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
El tipo del objeto es: <class 'numpy.ndarray'>
El numero de dimensiones es: 2
el numero de elementos es: 20
El tanaño de las dimensiones del objeto es: (4, 5)


In [44]:
print(type(mat_7.shape))
print(mat_7.shape[0])
print(mat_7.shape[1])

<class 'tuple'>
4
5


In [49]:
mat_9 = np.zeros((4,3))
print(f"El arreglo es :\n {mat_9}")
print(f"El tipo del objeto es: {type(mat_9)}")
print(f"El numero de dimensiones es: {mat_9.ndim}")
print(f"el numero de elementos es: {mat_9.size}")
print(f"El tanaño de las dimensiones del objeto es: {mat_9.shape}")

El arreglo es :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
El tipo del objeto es: <class 'numpy.ndarray'>
El numero de dimensiones es: 2
el numero de elementos es: 12
El tanaño de las dimensiones del objeto es: (4, 3)


In [51]:
mat_10 =  np.linspace(99,88,20) #
print(f"El arreglo es :\n {mat_10}\n")
print(f"El tipo del objeto es: {type(mat_10)}")
print(f"El numero de dimensiones es: {mat_10.ndim}")
print(f"el numero de elementos es: {mat_10.size}")
print(f"El tanaño de las dimensiones del objeto es: {mat_10.shape}")

El arreglo es :
 [99.         98.42105263 97.84210526 97.26315789 96.68421053 96.10526316
 95.52631579 94.94736842 94.36842105 93.78947368 93.21052632 92.63157895
 92.05263158 91.47368421 90.89473684 90.31578947 89.73684211 89.15789474
 88.57894737 88.        ]

El tipo del objeto es: <class 'numpy.ndarray'>
El numero de dimensiones es: 1
el numero de elementos es: 20
El tanaño de las dimensiones del objeto es: (20,)


In [53]:
type(mat_10.shape)

tuple