<a href="https://colab.research.google.com/github/NickTorres04/Programacion-en-Python-UTEC/blob/main/mod2_clase3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [1]:
# Arreglo que consume menos memoria.
import numpy as np

In [2]:
lista_1 = [1,3,5]
print(lista_1)
sum(lista_1)

[1, 3, 5]


9

In [3]:
type(lista_1)

list

In [4]:
mat_1=([2,4,5])
type(mat_1)

list

In [5]:
lista_1.append(8)
print(lista_1)

[1, 3, 5, 8]


In [6]:
vector = np.array([1, 2, 3, 4, 5])

In [7]:
type(vector)

numpy.ndarray

In [8]:
#listas:
l1 = [1,2,3]
l2 = [4,5,6]
l1+l2
print(l1+l2)

[1, 2, 3, 4, 5, 6]


In [9]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(f"Arreglo de Numpy 1 {a1}")
print(f"Arreglo de Numpy 1 {a2}")
print(f"Arreglo de Numpy a1 + a2 {a1+a2}")
print(f"Arreglo de Numpy a1 * a2 {a1*a2}")

Arreglo de Numpy 1 [1 2 3]
Arreglo de Numpy 1 [4 5 6]
Arreglo de Numpy a1 + a2 [5 7 9]
Arreglo de Numpy a1 * a2 [ 4 10 18]


In [10]:
mat_3 =np.array([1,2,3,4,5,6])
mat_3

array([1, 2, 3, 4, 5, 6])

## matriz de DOS DIMENSIONES

In [11]:
# Matriz en 2D
mat_4 = np.array([[1,2,3],[4,5,6]])
mat_4

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
mat_5 = np.array([[1],[4],[6]])
mat_5

array([[1],
       [4],
       [6]])

In [13]:
lista_2  =  [1,2,3,4,5]
print(f"La lista es : {lista_2}\n")
print(f"El tipo del objeto es: {type(lista_2)}")

La lista es : [1, 2, 3, 4, 5]

El tipo del objeto es: <class 'list'>


In [14]:
mat_5 =  np.array(lista_2)
print(f"La lista es : {mat_5}\n")
print(f"El tipo del objeto es: {type(mat_5)}")

La lista es : [1 2 3 4 5]

El tipo del objeto es: <class 'numpy.ndarray'>


In [15]:
lista_3  =  [[1,2,3],[4,5,6],[7,8,9]]
print(f"La lista es : {lista_3}\n")
print(f"El tipo del objeto es: {type(lista_3)}")

La lista es : [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

El tipo del objeto es: <class 'list'>


In [16]:
mat_6  =  np.array(lista_3)
print(f"La lista es :\n {mat_6}")
print(f"El tipo del objeto es: {type(mat_6)}")

La lista es :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
El tipo del objeto es: <class 'numpy.ndarray'>


In [17]:
mat_7 = np.arange(20).reshape(4,5) #FILAS , COLUMNAS
print(f"La lista es :\n {mat_7}")
print(f"El tipo del objeto es: {type(mat_7)}")
print(f"El numero de dimensiones es: {mat_7.ndim}")
print(f"el numero de elementos es: {mat_7.size}")
print(f"El tanaño de las dimensiones del objeto es: {mat_7.shape}")

La lista es :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
El tipo del objeto es: <class 'numpy.ndarray'>
El numero de dimensiones es: 2
el numero de elementos es: 20
El tanaño de las dimensiones del objeto es: (4, 5)


In [18]:
print(type(mat_7.shape))
print(mat_7.shape[0])
print(mat_7.shape[1])

<class 'tuple'>
4
5


In [19]:
mat_9 = np.zeros((4,3))
print(f"El arreglo es :\n {mat_9}")
print(f"El tipo del objeto es: {type(mat_9)}")
print(f"El numero de dimensiones es: {mat_9.ndim}")
print(f"el numero de elementos es: {mat_9.size}")
print(f"El tanaño de las dimensiones del objeto es: {mat_9.shape}")

El arreglo es :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
El tipo del objeto es: <class 'numpy.ndarray'>
El numero de dimensiones es: 2
el numero de elementos es: 12
El tanaño de las dimensiones del objeto es: (4, 3)


In [20]:
mat_10 =  np.linspace(99,88,20) #
print(f"El arreglo es :\n {mat_10}\n")
print(f"El tipo del objeto es: {type(mat_10)}")
print(f"El numero de dimensiones es: {mat_10.ndim}")
print(f"el numero de elementos es: {mat_10.size}")
print(f"El tanaño de las dimensiones del objeto es: {mat_10.shape}")

El arreglo es :
 [99.         98.42105263 97.84210526 97.26315789 96.68421053 96.10526316
 95.52631579 94.94736842 94.36842105 93.78947368 93.21052632 92.63157895
 92.05263158 91.47368421 90.89473684 90.31578947 89.73684211 89.15789474
 88.57894737 88.        ]

El tipo del objeto es: <class 'numpy.ndarray'>
El numero de dimensiones es: 1
el numero de elementos es: 20
El tanaño de las dimensiones del objeto es: (20,)


In [21]:
type(mat_10.shape)

tuple

In [22]:
np.arange(24).reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
mat_11 = np.arange(24).reshape(2,4,3)
print(f"El arreglo es :\n {mat_11}\n")
print(f"El tipo del objeto es: {type(mat_11)}")
print(f"El numero de dimensiones es: {mat_11.ndim}")
print(f"el numero de elementos es: {mat_11.size}")
print(f"El tanaño de las dimensiones del objeto es: {mat_11.shape}")

El arreglo es :
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]

El tipo del objeto es: <class 'numpy.ndarray'>
El numero de dimensiones es: 3
el numero de elementos es: 24
El tanaño de las dimensiones del objeto es: (2, 4, 3)


In [24]:
mat_11 = np.arange(24).reshape(6,2,2)
print(f"El arreglo es :\n {mat_11}\n")
print(f"El tipo del objeto es: {type(mat_11)}")
print(f"El numero de dimensiones es: {mat_11.ndim}")
print(f"el numero de elementos es: {mat_11.size}")
print(f"El tanaño de las dimensiones del objeto es: {mat_11.shape}")

El arreglo es :
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]

El tipo del objeto es: <class 'numpy.ndarray'>
El numero de dimensiones es: 3
el numero de elementos es: 24
El tanaño de las dimensiones del objeto es: (6, 2, 2)


In [25]:
mat_12 = np.arange(27).reshape(3,3,3)
print(f"El arreglo es :\n {mat_12}\n")
print(f"El tipo del objeto es: {type(mat_12)}")
print(f"El numero de dimensiones es: {mat_12.ndim}")
print(f"el numero de elementos es: {mat_12.size}")
print(f"El tanaño de las dimensiones del objeto es: {mat_12.shape}")

El arreglo es :
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

El tipo del objeto es: <class 'numpy.ndarray'>
El numero de dimensiones es: 3
el numero de elementos es: 27
El tanaño de las dimensiones del objeto es: (3, 3, 3)


In [26]:
mat_13 =np.arange(24).reshape(4,6)
mat_13

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

# ***CLASS***
Operaciones en matrices.

## ***Multiplicacion Vectorial:***

In [27]:
# Definición de los vectores
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Producto escalar
dot_product = np.dot(a, b)

print("Producto escalar:", dot_product)

Producto escalar: 32


In [28]:
# Definir dos vectores
vector1 = np.array([1, 0, 0])
vector2 = np.array([0, 1, 0])

# Calcular el producto cruzado
producto_cruzado = np.cross(vector1, vector2)

print("El producto cruzado es:", producto_cruzado)

El producto cruzado es: [0 0 1]


In [29]:
mat_12

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [30]:
mat_12[2].size

9

In [31]:
mat_13 =np.arange(16).reshape(4,4)
mat_13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
type(mat_13)

numpy.ndarray

## ***Suma add***

In [33]:
mat_18 =np.arange(4).reshape(2,2) + 1
mat_19 =np.arange(4).reshape(2,2) + 5
print(f"Arreglo 1 :\n {mat_18}\n")
print(f"Arreglo 2 :\n {mat_19}\n")

Arreglo 1 :
 [[1 2]
 [3 4]]

Arreglo 2 :
 [[5 6]
 [7 8]]



In [34]:
# add
print(f"Arreglo suma (mat_18 + mat_19) :\n {mat_18 + mat_19}\n")
print(f"Arreglo  add np.add(mat_18, mat_19) :\n {np.add(mat_18, mat_19)}\n")

Arreglo suma (mat_18 + mat_19) :
 [[ 6  8]
 [10 12]]

Arreglo  add np.add(mat_18, mat_19) :
 [[ 6  8]
 [10 12]]



## ***Resta subtract***

In [35]:
#np.subtract(vector1,vector2)
print(f"Arreglo resta (mat_18 - mat_19) :\n {mat_18 -  mat_19}\n")
print(f"Arreglo sub np.subtract(mat_18, mat_19) :\n {np.subtract(mat_18, mat_19)}\n")

Arreglo resta (mat_18 - mat_19) :
 [[-4 -4]
 [-4 -4]]

Arreglo sub np.subtract(mat_18, mat_19) :
 [[-4 -4]
 [-4 -4]]



## ***Multiply Multiplicacion***

In [36]:
#np.multiply(vector1, vector2)
print(f"Arreglo Multiplicacion (mat_18* mat_19) :\n {mat_18*mat_19}\n")
print(f"Arreglo np.multiply(mat_18, mat_19) :\n {np.multiply(mat_18, mat_19)}\n")

Arreglo Multiplicacion (mat_18* mat_19) :
 [[ 5 12]
 [21 32]]

Arreglo np.multiply(mat_18, mat_19) :
 [[ 5 12]
 [21 32]]



## ***Numeros Aleatorios***

In [37]:
n1 = np.random.randint(5)
mat_20 = np.random.randint(10, size=5)
mat_21 = np.random.randint(999, size=(3,3))
mat_22 =np.random.rand(10)
mat_23 = np.random.rand(3,3)
print(f"El numero aleatorio n1 es:\n{n1}\n")
print(f"La matriz aleatoria mat_20 es: \n{mat_20} \n")
print(f"La matriz aleatoria mat_21 es: \n {mat_21} \n")
print(f"La matriz aleatoria mat_22 es: \n{mat_22} \n")
print(f"La matriz aleatoria mat_23 es: \n {mat_23} \n")

El numero aleatorio n1 es:
1

La matriz aleatoria mat_20 es: 
[5 6 4 4 3] 

La matriz aleatoria mat_21 es: 
 [[714  16  34]
 [827 319 451]
 [ 94 820 304]] 

La matriz aleatoria mat_22 es: 
[0.32741008 0.23419607 0.27930058 0.38350027 0.63547413 0.75892848
 0.82572085 0.67998239 0.269962   0.71042826] 

La matriz aleatoria mat_23 es: 
 [[0.83191791 0.79560623 0.00663563]
 [0.36165603 0.11610236 0.96259359]
 [0.61236676 0.72664223 0.43591379]] 



In [38]:
mat_25 = np.random.choice([3,5,9,5,1],size=(2,2))
mat_26 = np.array([[0,1,2],[4,2,3]])
print(f"La matriz aleatoria mat_25 es: \n{mat_25} \n")
print(f"La matriz es de dimensiones: \n{mat_25.ndim}")
print(f"La matriz aleatoria mat_26 es: \n{mat_26} \n")
print(f"La matriz es de dimensiones de mat_26: {mat_26.ndim}")
print(f"El tipo de dato de mat_26: {type(mat_26)}")
print(f"La dimension de mat_26: {mat_26.shape}")

La matriz aleatoria mat_25 es: 
[[5 5]
 [1 9]] 

La matriz es de dimensiones: 
2
La matriz aleatoria mat_26 es: 
[[0 1 2]
 [4 2 3]] 

La matriz es de dimensiones de mat_26: 2
El tipo de dato de mat_26: <class 'numpy.ndarray'>
La dimension de mat_26: (2, 3)


In [39]:
# La suma de los valores de la matriz es:
print(f"La suma de los valores de la matriz es: {mat_26.sum()}")
# la suma de valores a nivel columna es:
print(f"La suma de los valores de la matriz es: {mat_26.sum(axis=0)}")
# La suma de valores a nivel filas:
print(f"La suma de los valores de la matriz es: {mat_26.sum(axis=1)}")

La suma de los valores de la matriz es: 12
La suma de los valores de la matriz es: [4 3 5]
La suma de los valores de la matriz es: [3 9]


In [40]:
mat_28 = np.array([[1,1],[1,1]])
mat_29 = np.array([[2,2],[2,2]])*4
print(f"La matriz mat_28 es: \n{mat_28} \n")
print(f"La matriz mat_29 es: \n{mat_29} \n")

La matriz mat_28 es: 
[[1 1]
 [1 1]] 

La matriz mat_29 es: 
[[8 8]
 [8 8]] 



## ***Concatenacion -  concatenate.***




In [41]:
np.concatenate([mat_28,mat_29])
print(f"np.concatenate([mat_28,mat_29]) :\n {np.concatenate([mat_28,mat_29])}")
# apilar vertical:
print(f"np.vstack([mat_28,mat_29]) :\n {np.concatenate([mat_28,mat_29],axis=0)}")
# apilar horizontal:
print(f"np.hstack([mat_28,mat_29]) :\n {np.concatenate([mat_28,mat_29],axis=1)}")

np.concatenate([mat_28,mat_29]) :
 [[1 1]
 [1 1]
 [8 8]
 [8 8]]
np.vstack([mat_28,mat_29]) :
 [[1 1]
 [1 1]
 [8 8]
 [8 8]]
np.hstack([mat_28,mat_29]) :
 [[1 1 8 8]
 [1 1 8 8]]
